### ISSUE TITLE
Error dialog does not resize when details are asked for

### ISSUE THREAD

**Issue by mattulbrich** [VerifAPS/stvs#20]
When an error dialog appears and I click on "Details anzeigen", the dialog becomes unreadable.

It cannot even not be resized anymore. Only after maximizing the dialog can I read the error details.

![Bildschirmfoto](https://cloud.githubusercontent.com/assets/17046629/26316958/3fee1be6-3f16-11e7-9e31-9524fe41b277.png)

### Details
* Ubuntu 16.04
* on commit 62f6b311b97f394dd3cfc3b0b99bd7aa0deb1c3c

**Comment by mattulbrich** [comment]
That commit sha was for the old repository.
Still a problem on a1b8e617cd2b55a1c018f796381891ef8e7776d2

**Comment by benjaminalt** [comment]
I had the same problem on Ubuntu GNOME, but not on Windows, so it seems to be a JavaFx Gnome bug. The dialog as it is right now was modeled according to [this post](http://code.makery.ch/blog/javafx-dialogs-official/); I looked for alternatives but the only real alternative that would also provide a scrollbar (for displaying arbitrarily long text) would have required implementing our own JavaFx dialog.

**Comment by csicar** [comment]
increase window size by default as a workaround

**Comment by csicar** [comment]
set localate for english error messages

**Comment by wadoon** [comment]
Remove stacktrace, put it into logging
