### ISSUE TITLE
Scale for integer values has non-integral labels.

### ISSUE THREAD

**Issue by mattulbrich** [VerifAPS/stvs#23]
For an integer variable that has only values 0 or 1, 1.5 is shown when displaying a counterexample. Spacing looks as if this is not the intended behaviour.

![screenshot_2017-05-22_18-36-41](https://cloud.githubusercontent.com/assets/17046629/26319061/cd6a6522-3f1d-11e7-8637-97ad70c6f66d.png)

System:
* xUbuntu 16.04
* Oracle java version "1.8.0_131"

Steps:  
Same example as in #22, but using `i >= 0` for the input constraint in the 2nd row.

**Comment by csicar** [comment]
The overlapping text can be fixed by increasing the distance between each timing-diagram row.
Since we only have integer values, the tick rate of the diagrams could be set to a minimum of 1.
