### ISSUE TITLE
Timing diagrams labels are badly placed (vertically)

### ISSUE THREAD

**Issue by mattulbrich** [VerifAPS/stvs#28]
When concretizing a table for the first, the labels can be badly placed. After changing something in the component, they are placed correctly (2nd image).

![screenshot_2017-06-02_14-46-01](https://cloud.githubusercontent.com/assets/17046629/26726313/c148b78e-47a2-11e7-8003-bd42bc07f750.png) ![screenshot_2017-06-02_14-47-09](https://cloud.githubusercontent.com/assets/17046629/26726316/c3e16360-47a2-11e7-9ef4-9d0d1a4b094a.png)

This does not seem to be reproducible every single time.

Spotted on a1b8e617cd2b55a1c018f796381891ef8e7776d2

related to #23

**Comment by csicar** [comment]
solved by 75ccfc23fb80f90cc22fed640d0ce97bf176e63b

**Comment by csicar** [comment]
initial positioning is wrong

**Comment by Lks18** [comment]
on windows the initial positioning is right.
seems to be a linux problem
<img width="489" alt="timingdiagrammlayout" src="https://user-images.githubusercontent.com/26623307/27686176-edaf5dca-5cd1-11e7-8341-4df96c9086f6.PNG">

**Comment by csicar** [comment]
inverst max. 1h for refresh, invalidate; find a workaround
