### ISSUE TITLE
Parsing of comments is wrong

### ISSUE THREAD

**Issue by mattulbrich** [VerifAPS/stvs#34]
Currently, comments are parsed beyond their end if there is a closing comment later.
I assume that greedy matching takes place here where it should not.

![bildschirmfoto_2017-06-26_15-02-42](https://user-images.githubusercontent.com/17046629/27540460-8c108dc6-5a80-11e7-8f22-20e9ff6d8f3f.png)

**Comment by wadoon** [comment]
![grafik](https://user-images.githubusercontent.com/104259/27712462-70037270-5d27-11e7-94ab-93c2c7fef0c7.png)
