### ISSUE TITLE
Syntax highlighting is broken

### ISSUE THREAD

**Issue by mattulbrich** [VerifAPS/stvs#35]
It seems the wrong characters are highlighted. The longer the code gets, the more are the highlights away from where they should be.

![bildschirmfoto_2017-06-26_15-25-32](https://user-images.githubusercontent.com/17046629/27541325-d4b5b03a-5a83-11e7-8751-c09763456b9a.png)

**Comment by wadoon** [comment]
For your color sub-pixel problem: https://stackoverflow.com/questions/18382969/can-the-rendering-of-the-javafx-2-8-font-be-improved

**Comment by wadoon** [comment]
The comment rule is correct: `'(*' .*? '*)' -> channel ( HIDDEN )`.

Maybe STVS uses an old version?

**Comment by mattulbrich** [comment]
It seems to be a problem with the lexer.
@wadoon investigates ...

**Comment by csicar** [comment]
check what lexer does with "!"

**Comment by wadoon** [comment]
Lexer skipts `!`. 

Lexer is aware of it in the next version.

**Comment by wadoon** [comment]
![grafik](https://user-images.githubusercontent.com/104259/27712663-560418ce-5d28-11e7-948b-c39ebd1096d4.png)

With the update of `iec61131lang` it seems to be more robust. 

Not all Keywords are highlighted! e.g. `exit`, `return`
