### ISSUE TITLE
Wizard Windows have no buttons

### ISSUE THREAD

**Issue by mattulbrich** [VerifAPS/stvs#42]
![bildschirmfoto_2017-07-17_08-21-34](https://user-images.githubusercontent.com/17046629/28257186-1b28fbee-6ac9-11e7-8275-1fc96f94e78c.png)

This is not urgent.

**Comment by wadoon** [comment]
Resize, the button are below the visible area.

see #37

**Comment by mattulbrich** [comment]
Duplicate of #37
